[app]
name = "Plane Radar"
category = "Apps"
wifi_preference = true

[entry]
class = "PlaneRadarApp"

[metadata]
author = "devnulluk"
license = "MIT"
url = "https://github.com/devnulluk/tildagon-plane-radar"
description = "Live aircraft radar with flexible location, flight following, fading trails and LED alerts."
version = "0.1.2"

[[metadata.capabilities]]
required = false
feature = { type = "Capability", identifier = "https://tildagon.badge.emfcamp.org/capabilities/registry/position/" }

[[metadata.capabilities]]
required = false
feature = { type = "Capability", identifier = "https://tildagon.badge.emfcamp.org/capabilities/registry/merged_neopixels/" }

[[metadata.capabilities]]
required = false
feature = { type = "2026 Frontboard" }
